FROM python:3.7

RUN apt-get update && apt-get install -y \
  curl \
  make \
  software-properties-common

RUN curl -sL https://deb.nodesource.com/setup_7.x | bash -

RUN apt-get update && apt-get install -y \
  npm \
  libldap2-dev \
  libsasl2-dev \
  libssl-dev

RUN pip install pip==20.3.2
RUN pip install -U \
  bandit \
  coveralls \
  setuptools==51.1.1

WORKDIR /app
COPY public-lemur /app/
RUN pip install -e .
RUN pip install "file://`pwd`#egg=lemur[dev]"
RUN pip install "file://`pwd`#egg=lemur[tests]"


# build frontend
# need to delete some left-overs from using submodules
WORKDIR /app
RUN rm /app/.git

# doesn't look like bower likes being root so we need --unsafe-perm here
RUN npm install --unsafe-perm
RUN python setup.py sdist bdist_wheel