add_header X-Frame-Options DENY;
add_header X-Content-Type-Options nosniff;
add_header X-XSS-Protection "1; mode=block";

map $time_iso8601 $time_iso8601_p1 {
    ~([^+]+) $1;
}

map $msec $millisec {
    ~\.([0-9]+)$ $1;
}

log_format json_combined
'{'
    '"timestamp":"$time_iso8601_p1.${millisec}000",'
    '"severity":"INFO",'
    '"log":"nginx",'
    '"httpRequest":{'
    '"requestMethod":"$request_method",'
    '"requestUrl":"$scheme://$host$request_uri",'
    '"requestSize":$request_length,'
    '"status":$status,'
    '"responseSize":$bytes_sent,'
    '"userAgent":"$http_user_agent",'
    '"remote_addr":"$remote_addr",'
    '"remoteIp":"$http_x_forwarded_for",'
    '"serverIp":"$server_addr",'
    '"referer":"$http_referer",'
    '"latency":"${request_time}s",'
    '"protocol":"$server_protocol"'
    '}'
'}';

server {
   listen      80;
   access_log  /dev/stdout  json_combined;
   error_log   /dev/stderr;


   resolver kube-dns.kube-system.svc.cluster.local valid=5s;
   set $backend "http://lemur-backend.cert-management.svc.cluster.local:8000";
   set $celeryflower "http://celery-flower.cert-management.svc.cluster.local:5555";

   location /api {
        proxy_pass $backend;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;    
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

   location /celery-flower/ {
        rewrite ^/celery-flower/(.*)$ /$1 break;
        proxy_pass $celeryflower;
        proxy_next_upstream error timeout invalid_header http_500 http_502 http_503 http_504;
        proxy_redirect off;
        proxy_buffering off;    
        proxy_set_header        Host            $host;
        proxy_set_header        X-Real-IP       $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location / {
        root /opt/lemur/static/;
        include mime.types;
        index index.html;
    }

}
