[supervisord]
nodaemon=true
user=root
logfile=/dev/null
logfile_maxbytes=0
pidfile = /tmp/supervisord.pid

[program:lemur]
environment = PYTHONUNBUFFERED=1
command=lemur start -b 0.0.0.0:8000
# TODO(jonaspalm): Change user to non-root (requires creating user first)
#                  During production we can probably split the API and the frontend into separate deployments
#                  and skip supervisor altogether.
user=root
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
user=root
redirect_stderr=true
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
