[tox]
envlist =
    lint,
    py37
indexserver =
    spotify = https://artifactory.spotify.net/artifactory/api/pypi/pypi/simple
isolated_build = True

[testenv]
deps = :spotify:-r{toxinidir}/requirements-test.txt
changedir = {toxinidir}/tests
commands =
  python3 -m pytest --cov-report=xml:cobertura/coverage.xml --cov-report=term-missing --junitxml=../test-reports/junit.xml --cov=plugin_dest_gcp

[testenv:lint]
basepython = python3.7
deps = :spotify:-r{toxinidir}/requirements-lint.txt
commands =
         python3 -m black . --diff --check
;         python3 -m pylint --rcfile={toxinidir}/pylintrc {toxinidir}/plugin_dest_gcp

[testenv:format]
; Autoformat the code, can be used to manually trigger a format if the linting fails
; run with tox -e format
basepython = python3.7
deps = :spotify:-r{toxinidir}/requirements-lint.txt
commands =
         python3 -m black .
