"""empty message

Revision ID: 327fdb19c31b
Revises: c301c59688d2
Create Date: 2021-03-01 17:34:21.786436

"""

# revision identifiers, used by Alembic.
revision = '327fdb19c31b'
down_revision = 'c301c59688d2'

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE TYPE certificatedestinationstate AS ENUM('PENDING', 'FAILED', 'UPLOADED')")

    op.add_column('certificate_destination_associations', sa.Column('data', sa.Text(), nullable=True))
    op.add_column('certificate_destination_associations', sa.Column('state', sa.Enum('PENDING', 'FAILED', 'UPLOADED', name='certificatedestinationstate'), nullable=True))
    op.add_column('certificate_destination_associations', sa.Column('uploaded_at', sqlalchemy_utils.types.arrow.ArrowType(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('certificate_destination_associations', 'uploaded_at')
    op.drop_column('certificate_destination_associations', 'state')
    op.drop_column('certificate_destination_associations', 'data')

    op.execute("DROP TYPE certificatedestinationstate")
    # ### end Alembic commands ###
