apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur-celery-flower
  namespace: cert-management
spec:
  selector:
    matchLabels:
      app: lemur-celery-flower
  template:
    metadata:
      labels:
        app: lemur-celery-flower
        role: spotifylemur
    spec:
      containers:
      - name: celery
        image: $DEPLOYMENT_IMAGE
        command: ["bash"]
        args: ["-c", "/opt/lemur/start-flower.sh"]
        env:
        - name: REDIS_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.REDIS_PASSWORD'
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi