apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur-celery-worker
  namespace: cert-management
spec:
  selector:
    matchLabels:
      app: lemur-celery-worker
  template:
    metadata:
      labels:
        app: lemur-celery-worker
        role: spotifylemur
    spec:
      containers:
      - name: lemur
        image: $DEPLOYMENT_IMAGE
        command: ["celery"]
        args: ["-A", "lemur.common.celery", "worker", "-l", "DEBUG", "--concurrency", "1", "-E"]
        env:
        - name: LEMUR_ENCRYPTION_KEYS
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.LEMUR_ENCRYPTION_KEYS'
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.SQLALCHEMY_DATABASE_URI'
        - name: DIGICERT_API_KEY 
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.DIGICERT_API_KEY'
        - name: REDIS_PASSWORD 
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.REDIS_PASSWORD'
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 1
            memory: 1Gi
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "-instances=xpn-cert-management:europe-west1:lemur=tcp:5432"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
