apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur
  namespace: cert-management 
spec:
  selector:
    matchLabels:
      app: lemur
  template:
    metadata:
      labels:
        app: lemur
        role: spotifylemur
    spec:
      containers:
      - name: lemur 
        image: $DEPLOYMENT_IMAGE
        env:
        - name: LEMUR_ENCRYPTION_KEYS
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'spotifylemur.LEMUR_ENCRYPTION_KEYS'
        - name: SQLALCHEMY_DATABASE_URI
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'lemur.SQLALCHEMY_DATABASE_URI'
        - name: LEMUR_TOKEN_SECRET
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'lemur.LEMUR_TOKEN_SECRET'
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'lemur.SECRET_KEY'
        - name: GOOGLE_SECRET
          valueFrom:
            secretKeyRef:
              name: 'lemur-secrets'
              key: 'lemur.GOOGLE_SECRET'
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/1/healthcheck
            port: http
            scheme: HTTP
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
      - name: cloudsql-proxy
        image: gcr.io/cloudsql-docker/gce-proxy:1.16
        command: ["/cloud_sql_proxy", "-instances=xpn-cert-management:europe-west1:lemur=tcp:5432"]
        securityContext:
          runAsUser: 2  # non-root user
          allowPrivilegeEscalation: false
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 2
            memory: 2Gi
