apiVersion: apps/v1
kind: Deployment
metadata:
  name: lemur
  namespace: cert-management
spec:
  selector:
    matchLabels:
      app: lemur
  template:
    metadata:
      labels:
        app: lemur
        role: spotifylemur
    spec:
      containers:
      - name: nginx
        command: ["/usr/sbin/nginx", "-g", "daemon off;"]
        image: $DEPLOYMENT_IMAGE
        ports:
        - name: http
          containerPort: 80
          protocol: TCP
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 2
            memory: 2Gi
