apiVersion: spotify.com/v1
kind: CeloSecret
metadata:
  name: lemur-secrets
  namespace: cert-management 
spec:
  role: spotifylemur 
  keys:
  - spotifylemur::LEMUR_ENCRYPTION_KEYS
  - spotifylemur::SQLALCHEMY_DATABASE_URI
  - spotifylemur::LEMUR_TOKEN_SECRET
  - spotifylemur::SECRET_KEY
  - spotifylemur::GOOGLE_SECRET
  - spotifylemur::DIGICERT_API_KEY
  - spotifylemur::REDIS_PASSWORD
